### ISSUE TITLE
String identifier prefix not needed

### ISSUE THREAD

**Issue by mudrd8mz** [nhoobin/moodle-auth_enrolkey#1]
This is not a real bug, just reporting it in case you would work on a new auth plugin in the future.

The "auth_token" prefix in string identifiers like `$string['auth_tokensignup_field']` is redundant. I am aware of the fact that the auth_email uses them. IIRC, there were legacy reasons for that as all the authentication plugins had originally shared a single strings file that only later was split into separate files (and the identifiers were not changed).

I don't think it needs to be changed now. As said, just for the future. Thanks.

**Comment by nhoobin** [comment]
I will take notice that the prefix identifier for the strings are no longer required.

Thanks.
