### ISSUE TITLE
Accessing plugin settings

### ISSUE THREAD

**Issue by mudrd8mz** [nhoobin/moodle-auth_enrolkey#2]
In auth.php constructor, you seem to call `get_config('auth/token')`. Given how the plugin settings are named (correctly), I doubt this actually works. You do not use the config now so you probably did not notice. I believe it should read `get_config('auth_token')`.

**Comment by nhoobin** [comment]
I did not notice at all. I have fixed so that it now correctly retrieves the values from the configuration plugin table if this becomes a requirement in the future.
